apiVersion: v1
kind: Service
metadata:
  name: victoria-service
spec:
  selector:
    app: victoria
  ports:
    - protocol: TCP
      port: 8428
      targetPort: 8428

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-deployment
  labels:
    app: victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria
  template:
    metadata:
      labels:
        app: victoria
    spec:
      containers:
        - name: victoria
          image: victoriametrics/victoria-metrics:stable
          ports:
            - containerPort: 8428

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoria-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: "victoria.olred.local"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: victoria-service
                port:
                  number: 8428