apiVersion: v1
kind: Service
metadata:
  name: victoria-service
spec:
  selector:
    app: victoria
  ports:
    - protocol: TCP
      port: 8428
      targetPort: 8428

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resources-reader
rules:
  - apiGroups: [""]
    resources:
      - services
      - pods
      - nodes
      - endpoints
    verbs:
      - list
      - watch
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dev
roleRef:
  kind: Role
  name: resources-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-config

data:
  vmconfig.yml: |
    scrape_configs:
      - job_name: victoriametrics
        static_configs:
          - targets: [ "localhost:8428" ]
      - job_name: "kubernetes-apiservers"
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels:
              [
                  __meta_kubernetes_namespace,
                  __meta_kubernetes_service_name,
                  __meta_kubernetes_endpoint_port_name,
              ]
            action: keep
            regex: default;kubernetes;https;
      - job_name: "kubernetes-nodes"
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [ __meta_kubernetes_node_name ]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics
      - job_name: "kubernetes-nodes-cadvisor"
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [ __meta_kubernetes_node_name ]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        metric_relabel_configs:
          - action: replace
            source_labels: [pod]
            regex: '(.+)'
            target_label: pod_name
            replacement: '${1}'
          - action: replace
            source_labels: [container]
            regex: '(.+)'
            target_label: container_name
            replacement: '${1}'
          - action: replace
            target_label: name
            replacement: k8s_stub
          - action: replace
            source_labels: [id]
            regex: '^/system\.slice/(.+)\.service$'
            target_label: systemd_service_name
            replacement: '${1}'


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-deployment
  labels:
    app: victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria
  template:
    metadata:
      labels:
        app: victoria
    spec:
      securityContext:
        supplementalGroups:
          - 0
      containers:
        - name: victoria
          image: victoriametrics/victoria-metrics:stable
          ports:
            - containerPort: 8428
          volumeMounts:
            - name: victoria-config
              mountPath: /victoria-metrics-test/
          args:
            - --promscrape.config=/victoria-metrics-test/vmconfig.yml
      volumes:
        - name: victoria-config
          configMap:
            name: victoria-config

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoria-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: "victoria.olred.local"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: victoria-service
                port:
                  number: 8428