---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yml: |
    apiVersion: 1
    
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        orgId: 1
        url: http://victoria-service:8428
        isDefault: true
        updateIntervalSeconds: 10

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-providers

data:
  dashboardproviders.yml: |
    apiVersion: 1
    providers:
      - name: 'Metrics'
        updateIntervalSeconds: 10
        allowUpdates: true
        orgId: 1
        folder: ''
        type: file
        editable: true
        options:
          path: /var/lib/grafana/dashboards/    


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:11.2.2
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "adminadmin"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-providers
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-kube-dashboard
              mountPath: /var/lib/grafana/dashboards
          resources:
            requests:
              memory: "500Mi"
              cpu: "50m"
            limits:
              memory: "1G"
              cpu: "50m"
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        
        - name: grafana-providers
          configMap:
            name: grafana-providers
        
        - name: grafana-kube-dashboard
          configMap:
            name: grafana-kube-dashboard

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: "grafana.olred.local"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000